# -*- coding: utf-8 -*-
"""Sql_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135XehF4JEklIWKU1XQdHK99IZx8UhjE2
"""

import pandas as pd
import numpy as np
import sqlite3
import random

conn = sqlite3.connect('sales_db.sqlite')  # Creates file 'sales_db.sqlite'
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS Sales (
        CustomerID INTEGER,
        CustomerName TEXT,
        ProductCode TEXT,
        ProductName TEXT,
        Quantity INTEGER,
        Price REAL,
        Amount REAL
    )
''')

products = {
    'P001': ('Shirt', 500),
    'P002': ('Pants', 800),
    'P003': ('Jeans', 1000)
}

import string

def random_name():
    return ''.join(random.choices(string.ascii_uppercase, k=5))

for i in range(1, 11):
    customer_id = i
    customer_name = random_name()
    product_code = random.choice(list(products.keys()))
    product_name, price = products[product_code]
    quantity = random.randint(1, 5)
    amount = quantity * price

    cursor.execute('''
        INSERT INTO Sales (CustomerID, CustomerName, ProductCode, ProductName, Quantity, Price, Amount)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (customer_id, customer_name, product_code, product_name, quantity, price, amount))

cursor.execute("SELECT * FROM Sales")
for row in cursor.fetchall():
    print(row)

query = '''
    SELECT
        ProductName,
        COUNT(*) AS TotalSales,
        SUM(Quantity) AS TotalQuantity,
        SUM(Price * Quantity) AS TotalRevenue,
        SUM(Quantity * Price) AS TotalQtyPrice
    FROM Sales
    GROUP BY ProductName
'''
df = pd.read_sql_query(query, conn)

print(df)

# Visualising the Result
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.bar(df['ProductName'], df['TotalRevenue'], color='skyblue')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.title('Total Revenue by Product')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

